<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ page.title }}</title>
    <link rel="stylesheet" href="stylesheets/master.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="stylesheets/syntax.css" type="text/css" media="screen" charset="utf-8">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
    <script src="javascripts/jquery.hint.js" type="text/javascript"></script>
    <script src="javascripts/jquery.pngFix.pack.js" type="text/javascript"></script>
  </head>

  <body>
    <a href="http://github.com/sbfaulkner/jquery.hint"><img style="position: absolute; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub" /></a>

    <div id="container">

      <div class="download">
        <a href="http://github.com/sbfaulkner/jquery.hint/zipball/master">
          <img border="0" width="60" src="http://github.com/images/modules/download/zip.png"></a>
        <a href="http://github.com/sbfaulkner/jquery.hint/tarball/master">
          <img border="0" width="60" src="http://github.com/images/modules/download/tar.png"></a>
        <p>Download this project in<br/>
          either
          <a href="http://github.com/sbfaulkner/jquery.hint/zipball/master">zip</a> or
          <a href="http://github.com/sbfaulkner/jquery.hint/tarball/master">tar</a> format.</p>
        <p class="clone">You can also clone this project from<br/>
          <a href="git://github.com/sbfaulkner/jquery.hint">git://github.com/sbfaulkner/jquery.hint</a></p>
      </div>

      {{ content }}

      <div class="footer">
        get the source code on GitHub : <a href="http://github.com/sbfaulkner/jquery.hint">sbfaulkner/jquery.hint</a>
      </div>

    </div>
    <script type="text/javascript">
      //<![CDATA[
      $(document).ready(function() {
        $(document).pngFix({blankgif:'images/transparent.gif'});
      });
      //]]>
    </script>
  </body>
</html>
